### ISSUE TITLE
new storage issue

### ISSUE THREAD

**Issue by ColaLiao** [Snownee/Harvest-Festival#16]
Mod Version:
Harvest-Festival-Legacy-1.12.2-0.6.15.jar

when crops put in to storage, the crops render position goes wrong.
農作物放入出貨籃的的顯示位置錯誤。

![image](https://user-images.githubusercontent.com/16384174/72968818-41e98800-3dff-11ea-9e75-8e9d3fbae42d.png)

P.S.
already test only use HFL mod.
已嘗試過只使用此模組。

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/75158062-55ff0d00-5750-11ea-9b17-5dee15be042d.png)
Cannot reproduce

**Comment by ColaLiao** [comment]
i try it again use only HF mod, still happen, i use forge 14.23.5.2847
HF 1.12.2-0.6.15

![image](https://user-images.githubusercontent.com/16384174/75159746-b0e63380-5753-11ea-87c4-fc1f9fd6a04f.png)

**Comment by Snownee** [comment]
I am using 2768. Could you please reproduce this in 2768 if you have time?

**Comment by ColaLiao** [comment]
i open lan game for my friend now.
i will try it tomorrow.

**Comment by ColaLiao** [comment]
i try 2768 and still happen, but i think i maybe found the problem.

it's all ok with just 1 or 2 crops inside.
![image](https://user-images.githubusercontent.com/16384174/75211446-e411dc80-57be-11ea-92ea-091b54e8dc7d.png)

![image](https://user-images.githubusercontent.com/16384174/75211617-70bc9a80-57bf-11ea-952c-994b81bd6176.png)


![image](https://user-images.githubusercontent.com/16384174/75211533-29cea500-57bf-11ea-9264-8e172c53babb.png)

but when put in over 3 crops in one stack...
![image](https://user-images.githubusercontent.com/16384174/75211663-9a75c180-57bf-11ea-8ee9-6cc26d9a5ee6.png)

![image](https://user-images.githubusercontent.com/16384174/75211668-a19ccf80-57bf-11ea-82e7-7dae835c3eab.png)

if i make them difference way like this
[1]
![image](https://user-images.githubusercontent.com/16384174/75211766-fb04fe80-57bf-11ea-8b4a-cb3b942d9cda.png)

or this
[2]
![image](https://user-images.githubusercontent.com/16384174/75211808-16700980-57c0-11ea-937a-fd4f410806d5.png)

and then put storage on the ground two times, the render will change to the other side
[1]
![image](https://user-images.githubusercontent.com/16384174/75211847-30115100-57c0-11ea-9029-ffb0a93fa1d9.png)

[2]
![image](https://user-images.githubusercontent.com/16384174/75211949-68189400-57c0-11ea-8354-50816eea132d.png)


and if put one stack and 1 crops.
the first time i put on the ground is ok.
![image](https://user-images.githubusercontent.com/16384174/75212152-fab93300-57c0-11ea-991d-fbf1ccd3d273.png)

![image](https://user-images.githubusercontent.com/16384174/75212136-f2f98e80-57c0-11ea-8fb1-987781a7c5e8.png)

but put it on the ground two times...
![image](https://user-images.githubusercontent.com/16384174/75212207-25a38700-57c1-11ea-9744-0a27920d752f.png)



conclusion:
1. happened when put in over two crops at first stack.
2. render change when put on the ground two times in difference condition.

pics for conclusion 1
![image](https://user-images.githubusercontent.com/16384174/75212609-6fd93800-57c2-11ea-8930-9aeeee8b1876.png)

![image](https://user-images.githubusercontent.com/16384174/75212619-77004600-57c2-11ea-8861-dfea1ff0031d.png)
