### ISSUE TITLE
[SUGGESTION] Better config options for more seeds and hoes

### ISSUE THREAD

**Issue by ghost** [Snownee/Harvest-Festival#2]
Hi, I really like your mod, well I'm glad that you port it to 1.12.2. Is there any chance that you would add option inside config file to add more seeds please ? In my pack which I'm creating are seeds from mods like natura, pam's harvestcraft, hemp seed from immersive engineering, hemp seed from ic2 classic, many seeds from fossils and archeology, mystical world, roots etc.. So it would be really nice if you could add custom seeds via config file and you could choose if they will grow in spring or summer etc. and add how many days to grow.

**Comment by owri** [comment]
Yes, please! I was hoping to add more seeds from Pam's etc and to have the option to have the various stores sell items from other mods

**Comment by nickjackson-ff** [comment]
CraftTweaker/MineTweaker used to support the old Harvest Legacy. I wonder if support could be re-added for the 1.12.x version of CraftTweaker.
http://minetweaker3.powerofbytes.com/wiki/Mods:Harvest_Festival_Support

**Comment by Snownee** [comment]
I think the CraftTweaker support has been added in the lastest release
