### ISSUE TITLE
Game crash when building goddess water

### ISSUE THREAD

**Issue by ColaLiao** [Snownee/Harvest-Festival#20]
Game crash when building goddess water.
建造女神之池時會在木匠放置女神池水的時候遊戲崩潰。

[crash-2020-02-23_00.34.04-client.txt](https://github.com/Snownee/Harvest-Festival/files/4243093/crash-2020-02-23_00.34.04-client.txt)

**Comment by Snownee** [comment]
Cannot reproduce

**Comment by ColaLiao** [comment]
use blueprint, and watch that guy work.
使用藍圖來建造，並且監工。

**Comment by Snownee** [comment]
Yes that is what I am doing

**Comment by ColaLiao** [comment]
but when that guy start put goddess water, my screen become the water color and than the game crash in seconds.

**Comment by ColaLiao** [comment]
I can only solve this problem by restart the game and leave that area before that guy start put goddess water again.

**Comment by ColaLiao** [comment]
i make a video, seems like Yulif put some block on the goddess water and then game crash.
test in both 2768 and 2847, and in video is using 2768.
only use HF mod and create new world.

https://drive.google.com/file/d/1FDxoKPl6If_3RAP4cXlkYgiUECNPnjht/view?usp=sharing

![HF0226](https://user-images.githubusercontent.com/16384174/75331815-52899400-58be-11ea-9d42-c70329d76017.png)

**Comment by Snownee** [comment]
Are you playing on a dedicated server?

**Comment by ColaLiao** [comment]
I play in singleplayer

**Comment by Snownee** [comment]
Could you upload your video to YouTube or somewhere else?

**Comment by ColaLiao** [comment]
https://www.youtube.com/watch?v=itMOiI4iydk

**Comment by Snownee** [comment]
seems fixed
