### ISSUE TITLE
Sold fish not showing in collection

### ISSUE THREAD

**Issue by Slither88** [Snownee/Harvest-Festival#22]
I am using the latest (14.23.5.2847) version of forge and Harvest Festival (0.6.16) and the fish I sold does not show in the collection tab of the farming for dummies book. Please see below:

![2020-02-25_08 24 37](https://user-images.githubusercontent.com/11262552/75220896-3811c680-57a9-11ea-8cf3-993ed1cb8d7c.png)

**Comment by Snownee** [comment]
you need to fish a fish to add

**Comment by Slither88** [comment]
Hi 
Thanks. Sorry for the erroneous report
