### ISSUE TITLE
Apple tree missing texture.

### ISSUE THREAD

**Issue by ColaLiao** [Snownee/Harvest-Festival#25]
Apple tree missing texture.

![image](https://user-images.githubusercontent.com/16384174/75683551-51979e80-5cd2-11ea-80eb-361586865884.png)

![image](https://user-images.githubusercontent.com/16384174/75683564-58beac80-5cd2-11ea-8380-66a86d4dd889.png)

**Comment by Snownee** [comment]
I do not know how to fix this
