### ISSUE TITLE
Eggs can not normally stack as well

### ISSUE THREAD

**Issue by ColaLiao** [Snownee/Harvest-Festival#28]
Eggs can not normally stack as well

its always make different stack

**Comment by Snownee** [comment]
I don't know what you mean

**Comment by ColaLiao** [comment]
like this

![image](https://user-images.githubusercontent.com/16384174/76159265-89cb3100-6159-11ea-9ab3-df5d9ec3fa78.png)

**Comment by Snownee** [comment]
I reviewed the code, found that the relationship point is stored in item NBT, which will help incubating egg

**Comment by ColaLiao** [comment]
is that means it will not change in future version?

**Comment by Snownee** [comment]
yes
