### ISSUE TITLE
Aether Legacy with Harvest Legacy

### ISSUE THREAD

**Issue by SmookePL** [Snownee/Harvest-Festival#3]
Hello
How to repair this? 
I have Aether Legacy in minecraft 1.12.2 and Harvest Festival Legacy, and launcher have error with aether. why?Enyone help me?

**Comment by nickjackson-ff** [comment]
Simply change the dimension ID for one of the mods. They both want to use dimension ID 4.

**Comment by SmookePL** [comment]
Okay but how to Change This id?

**Comment by nickjackson-ff** [comment]
You can change the value in one of these config files:

*aether_legacy.cfg*
```I:aether_dimension_id=4```

*harvestfestival.cfg*
```I:"Mining world ID"=4```

Just make sure the dimension ID isn't already in use. In Vanilla Minecraft, the Overworld is 0, the Nether is -1, and the End is 1.

**Comment by k978kiseki** [comment]
Also you could use "/forge dimensions" to check all the dimensions' id;
