### ISSUE TITLE
手持【市政厅建筑图纸】会闪退至主界面

### ISSUE THREAD

**Issue by qqq916366599** [Snownee/Harvest-Festival#32]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Admin'/12, l='MpServer', x=49.93, y=97.19, z=-507.49]]
  Chunk stats: MultiplayerChunkCache: 276, 276
  Level seed: 0
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (148,64,244), Chunk: (at 4,4,4 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 30570 game time, 11639 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 87 total; [EntityItem['item.tile.flower10'/5903, l='MpServer', x=67.75, y=73.00, z=-475.93], EntityDartFrogs['树蛙'/5914, l='MpServer', x=7.85, y=86.13, z=-477.50], EntityDartFrogs['树蛙'/5915, l='MpServer', x=6.50, y=86.00, z=-478.50], EntityItem['item.tile.torch'/5938, l='MpServer', x=58.13, y=29.00, z=-463.13], EntityDartFrogs['树蛙'/5172, l='MpServer', x=94.50, y=74.00, z=-540.50], EntityItem['item.tile.torch'/5941, l='MpServer', x=41.81, y=28.00, z=-461.59], EntityDartFrogs['树蛙'/5173, l='MpServer', x=95.63, y=74.00, z=-543.45], EntityItemFrame['物品展示框'/6197, l='MpServer', x=45.03, y=74.50, z=-485.50], EntityMinecartChest['运输矿车'/5942, l='MpServer', x=51.50, y=29.06, z=-461.50], EntityItemFrame['物品展示框'/6198, l='MpServer', x=45.97, y=76.50, z=-495.50], EntityMinecartChest['运输矿车'/5943, l='MpServer', x=51.50, y=29.06, z=-466.50], EntityItemFrame['物品展示框'/6199, l='MpServer', x=45.97, y=76.50, z=-493.50], EntityItemFrame['物品展示框'/6200, l='MpServer', x=45.97, y=76.50, z=-491.50], EntityMinecartChest['运输矿车'/4920, l='MpServer', x=21.50, y=36.06, z=-575.50], EntityItemFrame['物品展示框'/6201, l='MpServer', x=45.97, y=76.50, z=-489.50], EntityPainting['画'/6202, l='MpServer', x=44.00, y=76.50, z=-485.03], EntityItemFrame['物品展示框'/6203, l='MpServer', x=42.03, y=76.50, z=-486.50], EntityItemFrame['物品展示框'/6204, l='MpServer', x=42.03, y=76.50, z=-490.50], EntityItem['item.tile.torch'/5949, l='MpServer', x=86.35, y=24.00, z=-442.88], EntityItemFrame['物品展示框'/6205, l='MpServer', x=42.03, y=76.50, z=-494.50], EntityPainting['画'/6206, l='MpServer', x=50.97, y=78.50, z=-486.50], EntityItem['item.tile.torch'/5951, l='MpServer', x=44.54, y=39.00, z=-450.86], EntityItemFrame['物品展示框'/6207, l='MpServer', x=45.50, y=78.50, z=-491.03], EntityItem['item.tile.plant_1.root'/5952, l='MpServer', x=34.05, y=66.00, z=-443.20], EntityItemFrame['物品展示框'/6208, l='MpServer', x=45.50, y=78.50, z=-489.97], EntityWroughtnaut['钢铁骑士'/5953, l='MpServer', x=13.50, y=36.00, z=-447.50], EntityItemFrame['物品展示框'/6209, l='MpServer', x=45.97, y=79.50, z=-490.50], EntityItem['item.tile.epiph_artco'/5954, l='MpServer', x=79.88, y=73.00, z=-465.48], EntityPainting['画'/6210, l='MpServer', x=45.00, y=79.50, z=-495.97], EntityItemFrame['物品展示框'/6211, l='MpServer', x=45.50, y=80.50, z=-495.97], EntityItemFrame['物品展示框'/6212, l='MpServer', x=42.50, y=80.50, z=-495.97], EntityItemFrame['物品展示框'/6213, l='MpServer', x=50.97, y=81.50, z=-486.50], EntityItemFrame['物品展示框'/6214, l='MpServer', x=47.03, y=81.50, z=-486.50], EntityItemFrame['物品展示框'/6215, l='MpServer', x=44.50, y=81.50, z=-487.97], EntityItemFrame['物品展示框'/6216, l='MpServer', x=43.50, y=81.50, z=-487.97], EntityNPCVillager['Jenni'/6217, l='MpServer', x=45.51, y=74.06, z=-494.70], EntityNPCVillager['Candice'/6218, l='MpServer', x=43.50, y=79.00, z=-494.50], EntityItem['item.tile.log.birch'/6223, l='MpServer', x=46.50, y=74.00, z=-485.50], EntityItem['item.item.stick'/6224, l='MpServer', x=46.50, y=74.00, z=-485.50], EntityItem['item.item.dynamictrees:birchseed'/6225, l='MpServer', x=48.14, y=79.00, z=-489.74], EntityItem['item.item.dynamictrees:birchseed'/6226, l='MpServer', x=53.09, y=79.00, z=-487.31], EntityItem['item.item.dynamictrees:birchseed'/6227, l='MpServer', x=50.88, y=76.00, z=-487.21], EntityItem['item.item.dynamictrees:birchseed'/6228, l='MpServer', x=46.03, y=83.50, z=-491.27], EntityItem['item.item.dynamictrees:birchseed'/6229, l='MpServer', x=49.81, y=73.00, z=-477.74], EntityItem['item.item.dynamictrees:birchseed'/6230, l='MpServer', x=47.50, y=79.00, z=-487.89], EntityItem['item.item.dynamictrees:birchseed'/6231, l='MpServer', x=46.66, y=83.00, z=-486.06], EntityItem['item.item.dynamictrees:birchseed'/6233, l='MpServer', x=44.45, y=85.00, z=-486.20], EntityPainting['画'/6202, l='MpServer', x=44.00, y=76.50, z=-485.03], EntityPainting['画'/6206, l='MpServer', x=50.97, y=78.50, z=-486.50], EntityPainting['画'/6210, l='MpServer', x=45.00, y=79.50, z=-495.97], EntitySpider['蜘蛛'/6264, l='MpServer', x=17.50, y=13.00, z=-443.50], EntitySpider['蜘蛛'/6265, l='MpServer', x=14.50, y=13.00, z=-444.50], EntitySkeleton['骷髅'/6266, l='MpServer', x=13.50, y=13.00, z=-446.50], EntitySkeleton['骷髅'/6267, l='MpServer', x=15.50, y=13.00, z=-445.50], EntitySpider['蜘蛛'/6268, l='MpServer', x=118.50, y=60.00, z=-479.50], EntityMinecartChest['运输矿车'/4993, l='MpServer', x=31.50, y=25.06, z=-570.50], EntityItem['item.tile.grndc_twig'/6289, l='MpServer', x=42.13, y=76.00, z=-486.43], EntityPlayerSP['Admin'/12, l='MpServer', x=49.93, y=97.19, z=-507.49], EntityDeer['鹿'/5548, l='MpServer', x=101.21, y=69.00, z=-504.50], EntityDeer['鹿'/5549, l='MpServer', x=101.50, y=68.00, z=-506.50], EntityDeer['鹿'/5550, l='MpServer', x=98.29, y=69.00, z=-504.50], EntityItem['item.tile.flower_1.miners_delight'/6062, l='MpServer', x=113.61, y=19.00, z=-467.69], EntityDeer['鹿'/5551, l='MpServer', x=99.95, y=69.00, z=-504.50], EntityZombie['僵尸'/6321, l='MpServer', x=6.50, y=18.00, z=-513.50], EntitySkeleton['骷髅'/6322, l='MpServer', x=9.50, y=24.00, z=-572.50], EntityZombie['僵尸'/5556, l='MpServer', x=119.72, y=41.00, z=-529.52], EntitySpider['蜘蛛'/6328, l='MpServer', x=25.50, y=34.00, z=-426.50], EntitySpider['蜘蛛'/6330, l='MpServer', x=17.50, y=34.00, z=-426.50], EntityItem['item.tile.flower2.poppy'/5572, l='MpServer', x=2.63, y=78.00, z=-509.47], EntitySowOldSpot['斑点猪（母猪）'/4805, l='MpServer', x=-13.68, y=95.00, z=-523.72], EntityItem['item.tile.flower11'/5575, l='MpServer', x=84.47, y=71.00, z=-500.40], EntityItem['item.tile.mushroom0'/5576, l='MpServer', x=61.88, y=13.00, z=-510.88], EntityZombie['僵尸'/6344, l='MpServer', x=-3.50, y=21.00, z=-459.50], EntityItem['item.tile.mushroom14'/5577, l='MpServer', x=79.88, y=17.00, z=-500.13], EntityDartFrogs['树蛙'/5578, l='MpServer', x=39.49, y=89.00, z=-504.97], EntityDartFrogs['树蛙'/5579, l='MpServer', x=42.15, y=87.24, z=-502.50], EntityCreeper['爬行者'/6355, l='MpServer', x=47.50, y=39.00, z=-446.50], EntityItem['item.tile.torch'/5591, l='MpServer', x=30.09, y=31.00, z=-484.08], EntityMinecartChest['运输矿车'/5592, l='MpServer', x=32.50, y=27.06, z=-487.50], EntityItem['item.tile.torch'/5593, l='MpServer', x=69.59, y=31.00, z=-484.82], EntityItem['item.tile.mushroom.glowshroom'/5594, l='MpServer', x=47.13, y=17.00, z=-501.88], EntityMinecartChest['运输矿车'/5595, l='MpServer', x=80.50, y=28.06, z=-482.50], EntityItem['item.tile.flower11'/5596, l='MpServer', x=83.05, y=73.00, z=-495.07], EntityItem['item.tile.torch'/5086, l='MpServer', x=35.13, y=49.00, z=-547.88], EntityWroughtnaut['钢铁骑士'/5087, l='MpServer', x=43.50, y=48.00, z=-543.50], EntityItem['item.tile.mushroom.glowshroom'/5088, l='MpServer', x=46.88, y=37.00, z=-545.08], EntityItem['item.tile.mushroom.glowshroom'/5089, l='MpServer', x=46.88, y=37.00, z=-547.41]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_201, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2305135304 bytes (2198 MB) / 3976200192 bytes (3792 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 49 mods loaded, 49 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by Snownee** [comment]
请提供完整的报告
