### ISSUE TITLE
The stores are always closed

### ISSUE THREAD

**Issue by Cheezballe** [Snownee/Harvest-Festival#34]
I have tried everything to be able to purchase items from the NPCs. The correct times and days of the week for the store to be open but nope. I'm not sure if this is a bug or if I'm doing something wrong. I love this mode and I am glade it was brought to 1.12.2 and updated. Please help

**Comment by Snownee** [comment]
Cannot reproduce. you have to complete tasks first

**Comment by Cheezballe** [comment]
Thanks
