### ISSUE TITLE
Crafttweaker issue

### ISSUE THREAD

**Issue by teagan75** [Snownee/Harvest-Festival#38]
I cannot adjust the price of the immersive engineering seed bag via this script:

 //ShopName, PurchasableId, NewGoldCost
 mods.harvestfestival.Shops.adjustPurchasable("harvestfestival:general", "immersiveengineering_hempSeeds", 150);

**Comment by joe-vettek** [comment]
mods.harvestfestival.Shops.addPurchasable("harvestfestival:carpenter", <immersiveengineering:hempSeeds>, 10 );
use these instead of string
