### ISSUE TITLE
采矿场维度下的传送门显示石头材质

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [Snownee/Harvest-Festival#48]
模组版本：Harvest-Festival-Legacy-1.12.2-0.6.22
![2021-03-21_12 17 14](https://user-images.githubusercontent.com/37864486/111893711-8098c380-8a3f-11eb-9ef1-9954bb7e39a4.png)
单独拿出来其实是有和采矿场墙壁相结合的材质
![2021-03-21_12 19 32](https://user-images.githubusercontent.com/37864486/111893755-cb1a4000-8a3f-11eb-852b-340bbcc0d3e1.png)

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/114313100-bc4b1880-9b27-11eb-9396-ff7fd9209893.png)
无法复现

**Comment by mc-kaishixiaxue** [comment]
我忘了排除Optifine，抱歉
