### ISSUE TITLE
Issue with adding custom items to Shipment Box

### ISSUE THREAD

**Issue by Rukomura** [Snownee/Harvest-Festival#51]
Hello,
I tried adding new items to be shipped within the Shipment box, however, when I sleep and wake up the next day, the gold isn't updated and doesn't make any "kaching" sound. Otherwise, adding the items to the Shipment box works just fine.

This is the code I used for each item:

`mods.harvestfestival.Shipping.addShipping(<minecraft:wheat_seeds>, 25);`

I'm not sure if this is a bug or something that I'm missing...

**Comment by Snownee** [comment]
I can't reproduce it. It works for me

**Comment by Murrlin** [comment]
Which version was this for?
