### ISSUE TITLE
Lack of conversation data

### ISSUE THREAD

**Issue by CastleOrange** [Snownee/Harvest-Festival#54]
Error starry night

![2021-07-30_13 51 15](https://user-images.githubusercontent.com/88179676/127607486-c22a0356-a366-4951-a652-c8b69f17be8d.png)
![2021-07-30_13 51 23](https://user-images.githubusercontent.com/88179676/127607497-3f39f260-cada-4c61-a383-761efabae79e.png)

**Comment by Snownee** [comment]
it is unfinished content
