### ISSUE TITLE
矿场的电梯经常失灵

### ISSUE THREAD

**Issue by silite** [Snownee/Harvest-Festival#57]
你好Snownee，我是个萌新服主，现在开了个only Harvest-Festival mod 的服务器
在mod中，矿场的电梯偶尔会失灵
您看是mod的问题，还是我们的问题
解决与否，我之后会去爱发电支持您，独立开发辛苦了
![image](https://user-images.githubusercontent.com/32181762/145791791-a6e91d6d-7d11-4f5b-9136-e42e1b709d6e.png)
![image](https://user-images.githubusercontent.com/32181762/145791910-09bc700f-7f1e-4c18-a190-29506cafe632.png)

**Comment by Snownee** [comment]
应该是修复了

**Comment by silite** [comment]
看到了您今天上午的发版，辛苦了，请您喝杯咖啡
