### ISSUE TITLE
Simple season bug in the multiverse-core plug-in

### ISSUE THREAD

**Issue by jia-qi1** [Snownee/Harvest-Festival#59]
in 1.16.5
Simple seasons can only work in the main world. Using the multiverse-core plug-in in the server and creating other worlds will lead to the inability to grow crops. HUD cannot be displayed in the upper left corner of other worlds. I want it to work in every world and show HUD in the upper left corner

**Comment by jia-qi1** [comment]
Hi 雪尼(忘了加)

**Comment by Snownee** [comment]
？？？？？？？
和我有什么关系？

**Comment by jia-qi1** [comment]
aaaaa，对不起，我认错作者了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snownee/Harvest-Festival"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 凌晨2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snownee/Harvest-Festival] Simple season bug in the multiverse-core plug-in (Issue #59)





 
？？？？？？？
 和我有什么关系？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
