### ISSUE TITLE
Server Crash after Jade was killed.

### ISSUE THREAD

**Issue by EmyLightsaber** [Snownee/Harvest-Festival#60]
[crash-2023-05-14_21.00.06-server.txt](https://github.com/Snownee/Harvest-Festival/files/11472935/crash-2023-05-14_21.00.06-server.txt)
Thank you for reporting!
---

Java: 1.12.2 Forge: 14.23.5.2860
Server Crashes with above crash when a new day rolls around after I accidentally killed Jade. One of the chests in her room turned into a mimic, and then when I tried to kill the mimic, she got caught in the crossfire.

**Comment by EmyLightsaber** [comment]
It would appear it's actually happening after I place the shipment box you send things through to sell. It then crashes when I try to sleep after selling something.

**Comment by Snownee** [comment]
This has nothing to do with NPC being killed. That is because your ore dictionary is broken for some reason.
