### ISSUE TITLE
疑似会导致刷怪数量减少

### ISSUE THREAD

**Issue by ralseilii** [Snownee/Harvest-Festival#62]
已经把"Mobs in overworld only spawn under Y value"设置为300，但是感觉夜晚在地表的敌对生物数量还是减少了很多（还安装了yung的洞穴优化，DrZharks-MoCreatures-Extended-12.3.1和超多生物群系）

**Comment by ralseilii** [comment]
如果雪泥大佬能修复下地表刷怪量的问题就太感谢了，这个mod对我的整合包很重要

**Comment by Snownee** [comment]
请先确定问题确实存在
