### ISSUE TITLE
Destroy crops, no Drops.

### ISSUE THREAD

**Issue by al-wei** [Snownee/Harvest-Festival#64]
Harvest-Festival-Legacy-1.12.2-0.6.27.jar
Forge 14.23.5.2860
https://gist.github.com/al-wei/0906091ca45677492e1436a015eb331a

**Comment by Snownee** [comment]
please record a video on how to produce this problem

**Comment by al-wei** [comment]
> please record a video on how to produce this problem


https://github.com/Snownee/Harvest-Festival/assets/145486869/c91759e8-ac02-4384-b912-06375f0cdffe

**Comment by al-wei** [comment]
> > please record a video on how to produce this problem
> 
>  nd.mp4

A very ordinary process.

**Comment by Snownee** [comment]
这不是特性吗？
