### ISSUE TITLE
奶牛挤奶怎么出来的是小蛋黄酱。

### ISSUE THREAD

**Issue by mem0rz** [Snownee/Harvest-Festival#7]
奶牛挤奶怎么出来的是小蛋黄酱。
mods列表
![1](https://user-images.githubusercontent.com/14276116/69595087-73c9b280-1039-11ea-935a-f104786eda59.jpg)
![2](https://user-images.githubusercontent.com/14276116/69595088-762c0c80-1039-11ea-811a-d520c3534ff5.jpg)

Thank you for reporting!
---

 * Please upload your crash reports or logs to https://gist.github.com or similiar sites, don't just paste it in raw!
 * If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
 * Before reporting your issue, please make sure it have not already been reported.
 * Make sure you have the latest version of Harvest Festival, since your issue might already have been fixed!
 * Preferably provide us with what Forge version you are using. 
 * If the issue is between Harvest Festival and another mod, please inform what version of the mod you are using. Also make sure the other mod is updated to latest version.
 * Please check out https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/PLANS.md, before making any suggestions!

**Comment by Snownee** [comment]
据我测试未出现此问题。请确认只安装Harvest Festival的情况下是否能重现该问题。
