### ISSUE TITLE
Graphical glitch - Shipping Basket

### ISSUE THREAD

**Issue by Slither88** [Snownee/Harvest-Festival#8]
Hi

I am using Harvest-Festival-Legacy-1.12.2-0.6.5 with forge 14.23.5.2847.

I placed a shipping basket and right clicked it to get it on my head. I then shift-right clicked and placed some items inside. I then right clicked the shipping bin to ship the items. Everything seems to be working fine. Except that when I die with the basket it floats in the air where I died and becomes completely "invisible", I cannot interact with it. The items in the basket also stay rendered there even after trying to ship them.
![2019-11-30_10 10 54](https://user-images.githubusercontent.com/11262552/69897988-c9fd6500-135b-11ea-9510-d148f03ee51d.png)
![2019-11-30_10 10 29](https://user-images.githubusercontent.com/11262552/69897989-ccf85580-135b-11ea-9081-ae5db8f0ce8b.png)

**Comment by Snownee** [comment]
Run `/kill @e[type=harvestfestival:basket]` to remove **all** basket entities in world

I have uploaded a new release to fix bugs with basket

**Comment by Slither88** [comment]
Thanks.
